import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — BibleWise | ShelNova Labs",
  description:
    "Privacy Policy for BibleWise: AI Bible Study, developed by ShelNova Labs Ltd. Learn how we collect, use, and protect your data.",
};

export default function BibleWisePrivacyPolicy() {
  const updated = "22 July 2025";

  return (
    <div className="min-h-screen bg-snl-bg text-snl-text">
      {/* Top bar */}
      <div className="border-b border-snl-border">
        <div className="max-w-3xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="font-heading font-bold text-lg tracking-tight">
            Shel<span className="text-snl-violet">Nova</span> Labs
          </Link>
          <Link href="/privacy" className="text-snl-muted hover:text-snl-text text-sm transition-colors">
            ← All Privacy Policies
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <p className="text-snl-violet text-sm font-medium tracking-widest uppercase mb-3">
            Legal · BibleWise
          </p>
          <h1 className="font-heading text-4xl md:text-5xl font-bold text-snl-text mb-3">
            Privacy Policy
          </h1>
          <p className="text-snl-muted text-sm">Last updated: {updated}</p>
        </div>

        <div className="space-y-10 text-snl-muted leading-relaxed">

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">1. Introduction</h2>
            <p>
              ShelNova Labs Ltd. (&quot;ShelNova Labs&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) operates{" "}
              <span className="text-snl-text font-medium">BibleWise: AI Bible Study</span> (&quot;the App&quot;),
              a mobile application available on Android and iOS. This Privacy Policy explains what
              information we collect, how we use it, and your rights. By using BibleWise you agree to
              the practices described here.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">2. Information We Collect</h2>

            <h3 className="text-snl-text font-semibold mb-2 mt-4">2.1 Account Information</h3>
            <p className="mb-3">When you create an account we collect:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Email address and display name (via email/password sign-up or Google Sign-In)</li>
              <li>A unique user ID generated by Firebase Authentication</li>
              <li>Profile photo URL if provided by your Google account</li>
            </ul>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.2 App Activity Data</h3>
            <p className="mb-3">To personalise your experience and track your Bible study progress we store:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Bible chapters you have read and your reading history</li>
              <li>Bookmarks, highlights, and notes you create</li>
              <li>Study streaks, quiz scores, and progress statistics</li>
              <li>Reading plans you are enrolled in and their completion status</li>
            </ul>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.3 AI Coach Conversations</h3>
            <p>
              Messages you send to the AI Coach are transmitted to third-party AI providers (see Section 5)
              to generate a response. Conversation history is stored in your Firestore profile to enable
              context-aware follow-up responses. We do not use your conversations to train AI models.
            </p>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.4 Device &amp; Usage Data</h3>
            <p>
              We collect basic device information (device type, OS version) and crash reports through
              Firebase Crashlytics to diagnose bugs and improve stability. We do not collect precise
              location data.
            </p>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.5 Advertising Data</h3>
            <p>
              BibleWise uses Google AdMob to serve ads to free users. AdMob may collect your device&apos;s
              advertising identifier (GAID on Android, IDFA on iOS) and usage data to serve personalised
              or non-personalised advertisements. Please refer to{" "}
              <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer"
                className="text-snl-violet hover:underline">
                Google&apos;s Privacy Policy
              </a>{" "}
              for details on how AdMob handles data.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">3. How We Use Your Information</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>To authenticate you and secure your account</li>
              <li>To save and sync your Bible study progress across devices</li>
              <li>To power the AI Coach with relevant context from your reading history</li>
              <li>To enforce fair-use daily limits on free AI messages</li>
              <li>To send optional daily verse push notifications (only if you grant permission)</li>
              <li>To display advertisements to free users via Google AdMob</li>
              <li>To diagnose crashes and improve app stability via Firebase Crashlytics</li>
              <li>To prevent abuse of our AI services through moderation checks</li>
            </ul>
            <p className="mt-4">
              We do not sell, rent, or trade your personal information to any third party for marketing purposes.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">4. Data Storage &amp; Security</h2>
            <p className="mb-3">
              Your data is stored in{" "}
              <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer"
                className="text-snl-violet hover:underline">
                Google Firebase
              </a>{" "}
              (Firestore and Firebase Authentication), hosted in Google&apos;s secure cloud infrastructure.
              All data is transmitted over HTTPS. Firebase enforces server-side security rules ensuring
              users can only access their own data.
            </p>
            <p>
              No method of electronic transmission is 100% secure. While we take reasonable steps to protect
              your information, we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">5. Third-Party Services</h2>
            <p className="mb-5">
              BibleWise integrates the following third-party services. Each has its own privacy policy
              governing its data handling:
            </p>
            <div className="space-y-3">
              {([
                { name: "Google Firebase (Auth, Firestore, Crashlytics)", url: "https://firebase.google.com/support/privacy", purpose: "Authentication, data storage, crash reporting" },
                { name: "Google AdMob", url: "https://policies.google.com/privacy", purpose: "In-app advertising for free users" },
                { name: "OpenRouter", url: "https://openrouter.ai/privacy", purpose: "AI language model routing for AI Coach" },
                { name: "Fireworks AI", url: "https://fireworks.ai/privacy", purpose: "AI language model provider for AI Coach" },
                { name: "Mistral AI", url: "https://mistral.ai/privacy", purpose: "AI language model provider for AI Coach" },
              ] as const).map((s) => (
                <div key={s.name} className="bg-snl-card border border-snl-border rounded-lg px-5 py-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-1">
                  <div>
                    <p className="text-snl-text font-medium text-sm">{s.name}</p>
                    <p className="text-xs mt-0.5">{s.purpose}</p>
                  </div>
                  <a href={s.url} target="_blank" rel="noopener noreferrer" className="text-snl-violet text-xs hover:underline shrink-0">
                    Privacy Policy →
                  </a>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">6. Push Notifications</h2>
            <p>
              BibleWise may send daily verse notifications if you grant notification permission on your
              device. You can disable notifications at any time through your device&apos;s system settings.
              We do not send marketing or promotional push notifications without your explicit consent.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">7. Children&apos;s Privacy</h2>
            <p>
              BibleWise is not directed at children under the age of 13. We do not knowingly collect
              personal information from children. If you believe a child has created an account, please
              contact us and we will delete the account and associated data promptly.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">8. Data Retention</h2>
            <p>
              Your account data is retained for as long as your account is active. If you delete your
              account, your personal data and conversation history will be permanently deleted within
              30 days. Anonymised, aggregated usage statistics may be retained indefinitely.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">9. Your Rights</h2>
            <p className="mb-3">Depending on your location you may have the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Access the personal data we hold about you</li>
              <li>Request correction of inaccurate data</li>
              <li>Request deletion of your account and personal data</li>
              <li>Opt out of personalised advertising (via your device&apos;s ad settings)</li>
              <li>Object to or restrict certain processing of your data</li>
            </ul>
            <p className="mt-4">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:hello@shelnovalabs.com" className="text-snl-violet hover:underline">
                hello@shelnovalabs.com
              </a>.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. When we do, we will revise the
              &quot;Last updated&quot; date above. We encourage you to review this policy periodically.
              Continued use of BibleWise after changes are posted constitutes your acceptance of the
              updated policy.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">11. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy or how we handle your data, please reach out:</p>
            <div className="mt-4 bg-snl-card border border-snl-border rounded-xl p-5 space-y-1">
              <p className="text-snl-text font-medium">ShelNova Labs Ltd.</p>
              <p>Email:{" "}
                <a href="mailto:hello@shelnovalabs.com" className="text-snl-violet hover:underline">
                  hello@shelnovalabs.com
                </a>
              </p>
              <p>Website: shelnovalabs.com</p>
            </div>
          </section>

        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-snl-border mt-16">
        <div className="max-w-3xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-snl-muted text-xs">
            © {new Date().getFullYear()} ShelNova Labs Ltd. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="text-snl-muted hover:text-snl-text text-xs transition-colors">
              All Privacy Policies
            </Link>
            <Link href="/" className="text-snl-muted hover:text-snl-text text-xs transition-colors">
              shelnovalabs.com
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
