import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Sancta: Catholic Prayer & Bible | ShelNova Labs",
  description:
    "Privacy Policy for Sancta: Catholic Prayer & Bible App, developed by ShelNova Labs Ltd. Learn how we collect, use, and protect your data.",
};

export default function SanctaPrivacyPolicy() {
  const updated = "6 September 2026";

  return (
    <div className="min-h-screen bg-snl-bg text-snl-text">
      {/* Top bar */}
      <div className="border-b border-snl-border">
        <div className="max-w-3xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="font-heading font-bold text-lg tracking-tight">
            Shel<span className="text-snl-violet">Nova</span> Labs
          </Link>
          <Link href="/privacy" className="text-snl-muted hover:text-snl-text text-sm transition-colors">
            ← All Privacy Policies
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <p className="text-snl-violet text-sm font-medium tracking-widest uppercase mb-3">
            Legal · Sancta
          </p>
          <h1 className="font-heading text-4xl md:text-5xl font-bold text-snl-text mb-3">
            Privacy Policy
          </h1>
          <p className="text-snl-muted text-sm">Last updated: {updated}</p>
        </div>

        <div className="space-y-10 text-snl-muted leading-relaxed">

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">1. Introduction</h2>
            <p>
              ShelNova Labs Ltd. (&quot;ShelNova Labs&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) operates{" "}
              <span className="text-snl-text font-medium">Sancta: Catholic Prayer &amp; Bible</span> (&quot;the App&quot;),
              a mobile application available on Android and iOS. This Privacy Policy explains what information we collect, how we use it, and your choices regarding your personal data. By using Sancta, you agree to the practices described in this policy.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">2. Information We Collect</h2>

            <h3 className="text-snl-text font-semibold mb-2 mt-4">2.1 Account Information</h3>
            <p className="mb-3">When you create an account or sign in to Sancta, we collect:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Email address and display name (via email/password sign-up or Google Sign-In)</li>
              <li>A unique user ID generated by Firebase Authentication</li>
              <li>Profile photo URL (if provided by your Google account)</li>
              <li>Guest / Anonymous authentication token if you use the app without registering</li>
            </ul>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.2 Prayer &amp; App Activity Data</h3>
            <p className="mb-3">To sync your spiritual progress and personalize your experience, we store:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Prayer streaks, completed Rosary decades, and daily devotion records</li>
              <li>Bookmarked Bible verses, highlights, and personal journal notes</li>
              <li>Custom prayer intentions and audio prayer playback settings</li>
              <li>Liturgical calendar preferences and audio download history</li>
            </ul>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.3 Device &amp; Technical Diagnostics</h3>
            <p>
              We collect non-personally identifiable technical information (device model, operating system version, app version, language preference) and crash logs through Firebase Crashlytics to diagnose bugs and maintain high app performance. We do not track precise GPS location data.
            </p>

            <h3 className="text-snl-text font-semibold mb-2 mt-6">2.4 Advertising Data</h3>
            <p>
              Sancta uses Google AdMob to serve advertisements to users on the free tier. AdMob may collect your device&apos;s advertising identifier (GAID on Android, IDFA on iOS) and app interaction events to deliver non-intrusive ads. For details on how Google processes advertising data, visit{" "}
              <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer"
                className="text-snl-violet hover:underline">
                Google&apos;s Privacy Policy
              </a>.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">3. How We Use Your Information</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>To authenticate your account and securely sync prayer data across your devices</li>
              <li>To maintain your prayer streaks, Bible bookmarks, and personal journal entries</li>
              <li>To deliver local prayer reminders and daily liturgical notification alerts (with permission)</li>
              <li>To display non-intrusive advertisements via Google AdMob</li>
              <li>To diagnose technical crashes, improve app speed, and optimize offline audio playback</li>
              <li>To process subscription statuses or in-app purchases where applicable</li>
            </ul>
            <p className="mt-4">
              We never sell, rent, or trade your personal data or spiritual notes to third parties for marketing purposes.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">4. Data Storage &amp; Encryption</h2>
            <p className="mb-3">
              Your profile data and prayer logs are securely encrypted in transit using HTTPS/TLS protocols and stored in{" "}
              <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer"
                className="text-snl-violet hover:underline">
                Google Firebase
              </a>{" "}
              (Firestore and Firebase Authentication) hosted on secure Google Cloud infrastructure. Strict server-side security rules ensure users can only access their own data.
            </p>
            <p>
              Audio recordings (such as Rosary tracks or Bible audio) and offline liturgical calendars are cached locally on your device storage to support offline usage.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">5. Third-Party Service Providers</h2>
            <p className="mb-5">
              Sancta integrates trusted third-party services to deliver core app functionality:
            </p>
            <div className="space-y-3">
              {[
                { name: "Google Firebase (Auth, Firestore, Crashlytics)", url: "https://firebase.google.com/support/privacy", purpose: "Authentication, secure cloud sync, and crash analytics" },
                { name: "Google AdMob", url: "https://policies.google.com/privacy", purpose: "In-app advertising on free accounts" },
                { name: "Google Play Services / Apple App Store", url: "https://play.google.com/about/privacy-security-deception/", purpose: "App delivery, updates, and in-app purchase verification" },
              ].map((s) => (
                <div key={s.name} className="bg-snl-card border border-snl-border rounded-lg px-5 py-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-1">
                  <div>
                    <p className="text-snl-text font-medium text-sm">{s.name}</p>
                    <p className="text-xs mt-0.5">{s.purpose}</p>
                  </div>
                  <a href={s.url} target="_blank" rel="noopener noreferrer" className="text-snl-violet text-xs hover:underline shrink-0">
                    Privacy Policy →
                  </a>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">6. Push Notifications &amp; Reminders</h2>
            <p>
              Sancta provides optional local reminders for daily prayer, Rosary intention alarms, and daily Gospel readings. Notifications are scheduled locally on your device. You can turn off or adjust reminder times at any time in the app settings or via system notifications settings.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">7. Account &amp; Data Deletion</h2>
            <p className="mb-3">
              You have the right to request the deletion of your account and all associated personal data at any time.
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>
                <span className="text-snl-text font-medium">In-App Deletion:</span> Go to <span className="text-snl-text font-medium">Profile → Settings → Account → Delete Account</span> inside the Sancta app to instantly erase your account and Firestore data.
              </li>
              <li>
                <span className="text-snl-text font-medium">Web Request:</span> Visit our dedicated{" "}
                <Link href="/sancta/delete-account" className="text-snl-violet hover:underline">
                  Sancta Account Deletion Page
                </Link>{" "}
                to submit an online deletion request or email us at{" "}
                <a href="mailto:hello@shelnovalabs.com" className="text-snl-violet hover:underline">
                  hello@shelnovalabs.com
                </a>.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">8. Children&apos;s Privacy</h2>
            <p>
              Sancta is designed for users of all ages as a devotional prayer tool, but is not intended to collect personal data from children under 13. We do not knowingly collect personal information from children under 13. If you believe a child has created an account without parental consent, please contact us for immediate account deletion.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">9. Your Rights</h2>
            <p className="mb-3">Depending on your region, you have the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Access the personal information linked to your account</li>
              <li>Request correction or deletion of your account data</li>
              <li>Opt out of personalized advertising in your device ad settings</li>
              <li>Export or download your journal notes and bookmarks</li>
            </ul>
            <p className="mt-4">
              To exercise these rights, contact us at{" "}
              <a href="mailto:hello@shelnovalabs.com" className="text-snl-violet hover:underline">
                hello@shelnovalabs.com
              </a>.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy periodically. Any revisions will be reflected with an updated &quot;Last updated&quot; date at the top of this page. Continued use of Sancta following any changes indicates acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-snl-text mb-3">11. Contact Us</h2>
            <p>If you have any questions or feedback regarding Sancta&apos;s Privacy Policy or data handling, please reach out to us:</p>
            <div className="mt-4 bg-snl-card border border-snl-border rounded-xl p-5 space-y-1">
              <p className="text-snl-text font-medium">ShelNova Labs Ltd.</p>
              <p>Email:{" "}
                <a href="mailto:hello@shelnovalabs.com" className="text-snl-violet hover:underline">
                  hello@shelnovalabs.com
                </a>
              </p>
              <p>Website: shelnovalabs.com</p>
            </div>
          </section>

        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-snl-border mt-16">
        <div className="max-w-3xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-snl-muted text-xs">
            © {new Date().getFullYear()} ShelNova Labs Ltd. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="text-snl-muted hover:text-snl-text text-xs transition-colors">
              All Privacy Policies
            </Link>
            <Link href="/sancta/delete-account" className="text-snl-muted hover:text-snl-text text-xs transition-colors">
              Delete Account
            </Link>
            <Link href="/" className="text-snl-muted hover:text-snl-text text-xs transition-colors">
              shelnovalabs.com
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
